language: node_js
node_js:
- '0.10'
sudo: false
addons:
  code_climate:
    repo_token:
      secure: Ol0MUyYYNUGLDy0VluDMP+rmG2LAG0f0URDvV5hoXM2fDJEaF50ptVOJUt7TZT3yJHneuRFQcRgPTOKKYDrtRECGuE44lQdigTZCkwYx7GDcAIiyiqzAyZqf62DhTBvgAk4K/lm1VwF2XV1aydEqUmc8Xvq+eqevDgP4IZCIu14=
script:
- npm run cover
after_script:
- npm run publish-coverage
before_deploy:
- npm run release
deploy:
  provider: releases
  api_key:
    secure: ObsgOKwxmbfJWH7cJOgbN0LxR4qq5O9TY1wMCA4J00f9zenZGzP4gyO1Tw2MNBmAJuNK3rvdv+qSEV7jgExCyyPhw7be0mDjGaY6/e+kqclYuqRXjc+TUigm+hUxCsRj3nYvl+gjcJCnzHX658fbED/uf07IbyLSqNh1PToKh0M=
  skip_cleanup: true
  file_glob: true
  file: release/papaya-*
  on:
    repo: justinhoward/papaya
    tags: true
