language: node_js
node_js:
- '0.10'
addons:
  code_climate:
    repo_token:
      secure: Ol0MUyYYNUGLDy0VluDMP+rmG2LAG0f0URDvV5hoXM2fDJEaF50ptVOJUt7TZT3yJHneuRFQcRgPTOKKYDrtRECGuE44lQdigTZCkwYx7GDcAIiyiqzAyZqf62DhTBvgAk4K/lm1VwF2XV1aydEqUmc8Xvq+eqevDgP4IZCIu14=
script:
- npm run cover
after_script:
- npm run publish-coverage
